module.exports = [
  "how was your day",
  "did you have fun today",
  "blue",
  "black",
  "green",
  "yellow",
  "stop dont go",
  "i like cookies",
  "orange",
  "pink",
  "purple",
  "tan",
  "how often do you shop",
  "please dont stop the music",
  "iphone",
  "headset",
  "toys",
  "cards",
  "penicle",
  "baby",
  "staple",
  "mouse",
  "animals",
  "dog",
  "cat",
  "snake",
  "boy",
  "gitbash",
  "girl",
  "how about those apples",
  "jog",
  "what more do you want",
  "couch",
  "ps4",
  "xbox",
  "picture",
  "cars",
  "what about gum",
  "cup",
  "hot",
  "basketball",
  "soccer",
  "corn dog",
  "corn hole",
  "football",
  "baseball",
  "career",
  "job",
  "notebook",
  "how can i help",
  "can you guess what i am saying",
  "how many times do i have to tell you",
  "chocolate",
  "peanuts",
  "coffee",
  "bike",
  "ball",
  "why dont you like me",
  "how often do you ski",
  "lets jump around",
  "more and more",
  "around the world",
  "why cant i stop",
  "stop i dont want to play",
  "join my team",
  "slim jim eat me",
  "what more can i ask for",
  "do you love me",
  "happy birthday to you",
  "what songs do you like",
  "how often do you run",
  "how tall are you",
  "why dont you just believe me",
  "can you make a hook shot",
  "way to stay in the game",
  "can i ask you something",
  "do you like fish",
  "can you swim",
  "can you play basketball",
  "how high can you jump",
  "i dont like when you do that",
  "air up there",
  "stop drop and roll",
  "more to come",
  "jump shot",
  "do you go there everyday",
  "did you plan on seeing me",
  "dont guess to many wrong",
  "hold my hand",
  "do you think that will work",
  "more and more questions",
  "stop what you are doing",
  "i cant take you serious",
  "do you smell what the rock is cooking",
  "wwe",
  "bowling",
  "do you smell that",
  "how about now",
  "i love to code"
];
